name: CI / Docker

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ '**.md', '**.svg']
  pull_request:
    branches: [ "**" ]
    paths-ignore: [ '**.md', '**.svg' ]
  workflow_dispatch:

jobs:
  build_images:
    runs-on: ubuntu-latest
    name: Build Docker Images
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Frontend Image
        run: |
          docker build --file frontend/Dockerfile -t collabshare-frontend:${{ github.sha }} ./frontend
          echo "Frontend image built successfully"

      - name: Build Backend Image
        run: |
          docker build --file backend/Dockerfile -t collabshare-backend:${{ github.sha }} ./backend
          echo "Backend image built successfully"