name: CI / Docker

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ '**.md', '**.svg']
  pull_request:
    branches: [ "**" ]
    paths-ignore: [ '**.md', '**.svg' ]
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    name: Build Frontend Image
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Frontend Docker Image
      run: cd frontend; docker build --file Dockerfile -t collabshare-frontend:${{ github.sha }}

  build_backend:
    runs-on: ubuntu-latest
    name: Build Backend Image
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Backend Docker Image
      run: cd backend; docker build --file Dockerfile -t collabshare-backend:${{ github.sha }}
